Update extension-grants.rst with example
oauthjs/node-oauth2-server pull request #530
Opened 2018-10-16 20:13 UTC by ionizer

Updated documentation to describe how to implement custom grant types

2018-10-18 07:25 UTC, maxtruxa requested changes
Thanks for the PR. Could you look at the suggested changes?

2018-10-23 11:12 UTC, ionizer commented on docs/misc/extension-grants.rst
> +  let AbstractGrantType = require('oauth2-server/lib/grant-types/abstract-grant-type');
Sorry for the late response. I wasn't aware about this when making my example. Thanks.

2018-10-23 11:21 UTC, ionizer commented on docs/misc/extension-grants.rst
> +This might require you to add the new ``grant_type`` into the ``client`` data
Sorry for being not so good at explaining this. But at least in my implementation, I perform checks against my ``client``'s ``grant_type`` data in the database, whether the grant type is valid or not. I'm still wondering how to best explain this.

2018-10-23 11:22 UTC, ionizer commented on docs/misc/extension-grants.rst
> +Extension grants are registered through `OAuth2Server#token() <https://oauth2-server.readthedocs.io/en/latest/api/oauth2-server.html#token-request-response-options-callback>`_ (``options.extendedGran
I've changed it back the way it was

2018-10-23 11:29 UTC, ionizer commented on docs/misc/extension-grants.rst
> +          }
Should have fixed it on my new commit.

2025-07-22 07:58 UTC, closed without merging